name: Build and Upload Container Images

run-name: Build Container Image

on: [push]

jobs:
  Publish-Container-Image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install Docker
        run: curl -fsSL https://get.docker.com | sh
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image for Java 8
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Java8-Dockerfile
          push: true
          tags: "ghcr.io/timystream/mjrt:8"
      - name: Build and push Docker image for Java 11
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Java11-Dockerfile
          push: true
          tags: "ghcr.io/timystream/mjrt:11"
      - name: Build and push Docker image for Java 17
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Java17-Dockerfile
          push: true
          tags: "ghcr.io/timystream/mjrt:17"
      - name: Build and push Docker image for Java 21
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Java21-Dockerfile
          push: true
          tags: "ghcr.io/timystream/mjrt:21"
